### ISSUE TITLE
openGL error on mac os sierra

### ISSUE THREAD

**Issue by louisdoctor** [FXIhub/owl#28]
Here is the full traceback:

Traceback (most recent call last):
  File "/Users/louisdoctor/software/owl/views/view2d.py", line 825, in paintGL
    GL.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT)
  File "/usr/local/lib/python2.7/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/usr/local/lib/python2.7/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1286,
	description = 'invalid framebuffer operation',
	baseOperation = glClear,
	cArguments = (16640,)
)

**Comment by louisdoctor** [comment]
I am using this graphiccard:

Intel Iris 1536 MB
